# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoolParks tool
                                 A QGIS plugin
 Coolparks toolbox
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-07-06
        copyright            : (C) 2023 by Jérémy Bernard
        email                : jeremy.bernard@zaclys.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jérémy Bernard'
__date__ = '2023-07-06'
__copyright__ = '(C) 2023 by Jérémy Bernard'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProcessingCoolParksTool class from file ProcessingCoolParksTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .processing_coolparks import ProcessingCoolParksPlugin
    return ProcessingCoolParksPlugin()
